"""empty message

Revision ID: 024e087fd3a5
Revises: 2807edd385a2
Create Date: 2021-11-16 14:19:42.633535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024e087fd3a5'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###
